language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
  intent_tokenization_flag: true
  intent_split_symbol: +
policies:
- name: MemoizationPolicy
- name: KerasPolicy
  epochs: 200
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.2
  core_threshold: 0.2
  fallback_action_name: action_default_fallback
